# Generated by Django 5.2.17 on 2026-09-12 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='OwnershipPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_name', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['start_date'],
            },
        ),
        migrations.CreateModel(
            name='RevenueContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('source_type', models.CharField(choices=[('PARKING', '停车位'), ('AD', '广告位'), ('OTHER', '其他')], max_length=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('period_start', models.DateField(help_text='收入归属期起')),
                ('period_end', models.DateField(help_text='收入归属期止')),
                ('received_date', models.DateField(help_text='实际收款日期,与归属期无关')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AllocationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_no', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('scope_type', models.CharField(choices=[('ALL', '全体业主'), ('BUILDINGS', '指定楼栋')], default='ALL', max_length=10)),
                ('method', models.CharField(choices=[('BY_AREA', '按建筑面积'), ('FIXED_SHARE', '固定份额')], default='BY_AREA', max_length=12)),
                ('exclude_vacant', models.BooleanField(default=False)),
                ('vacant_basis', models.FileField(blank=True, help_text='剔除空置房的依据文件,必传', null=True, upload_to='basis/')),
                ('shortfall_policy', models.CharField(choices=[('SCALE', '份额不足按比例放大'), ('RESERVE', '份额不足部分结余留存')], default='RESERVE', max_length=10)),
                ('publication_days', models.PositiveIntegerField(default=7, help_text='公示天数,期内不可结转')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('supersedes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='superseded_by', to='revenue.allocationrule')),
                ('buildings', models.ManyToManyField(blank=True, help_text='受益范围限定的楼栋', to='revenue.building')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='revenue.revenuecontract')),
            ],
        ),
        migrations.CreateModel(
            name='AllocationVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_no', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('DRAFT', '草稿'), ('PUBLISHED', '公示中'), ('CARRIED', '已结转')], default='DRAFT', max_length=10)),
                ('allocated_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('unallocated_amount', models.DecimalField(decimal_places=2, default=0, help_text='份额不足等原因未分配的结余', max_digits=14)),
                ('computed_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='revenue.allocationrule')),
            ],
            options={
                'ordering': ['-computed_at'],
                'unique_together': {('rule', 'version_no')},
            },
        ),
        migrations.CreateModel(
            name='AllocationDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_name', models.CharField(max_length=100)),
                ('slice_start', models.DateField(help_text='该明细覆盖的归属期片段起')),
                ('slice_end', models.DateField(help_text='该明细覆盖的归属期片段止')),
                ('share', models.DecimalField(decimal_places=8, help_text='占总收益的比例', max_digits=14)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('remainder_applied', models.BooleanField(default=False, help_text='尾差调整标记(+0.01)')),
                ('frozen_amount', models.DecimalField(decimal_places=2, default=0, help_text='异议冻结金额', max_digits=14)),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='revenue.allocationversion')),
                ('ownership_period', models.ForeignKey(help_text='追溯到权属期间', null=True, on_delete=django.db.models.deletion.PROTECT, to='revenue.ownershipperiod')),
            ],
            options={
                'ordering': ['unit__building_id', 'unit__code', 'slice_start'],
            },
        ),
        migrations.CreateModel(
            name='CarryForward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='实际结转金额(扣除冻结)', max_digits=14)),
                ('frozen_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('carried_at', models.DateTimeField(auto_now_add=True)),
                ('version', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='carry_forward', to='revenue.allocationversion')),
            ],
        ),
        migrations.CreateModel(
            name='Adjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delta', models.DecimalField(decimal_places=2, help_text='正为补分,负为扣回', max_digits=14)),
                ('reason', models.CharField(max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('detail', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adjustments', to='revenue.allocationdetail')),
                ('carry_forward', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adjustments', to='revenue.carryforward')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Dispute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('OPEN', '未处理'), ('RESOLVED', '已处理')], default='OPEN', max_length=10)),
                ('resolution', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disputes', to='revenue.allocationdetail')),
            ],
        ),
        migrations.CreateModel(
            name='ContractAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='contracts/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='revenue.revenuecontract')),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('area', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_vacant', models.BooleanField(default=False, help_text='空置房,无依据不得从受益基数剔除')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='revenue.building')),
            ],
            options={
                'ordering': ['building_id', 'code'],
                'unique_together': {('building', 'code')},
            },
        ),
        migrations.AddField(
            model_name='ownershipperiod',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ownership_periods', to='revenue.unit'),
        ),
        migrations.AddField(
            model_name='allocationdetail',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='revenue.unit'),
        ),
        migrations.CreateModel(
            name='RuleShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share', models.DecimalField(decimal_places=6, max_digits=9)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='revenue.allocationrule')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='revenue.unit')),
            ],
            options={
                'unique_together': {('rule', 'unit')},
            },
        ),
    ]
